// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmsnsnfqufykwpesnjup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tc25zbmZxdWZ5a3dwZXNuanVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0MDQxNjEsImV4cCI6MjA3Mzk4MDE2MX0.XV_tASDS5Z2WeZssB4Tr2BMkEw6CjXMb_TKlSILFJUM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});